<a href="https://colab.research.google.com/github/Abhi050/NLP-/blob/main/Word_Embedding_NLP.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
!pip install tensorflow-gpu

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/


In [4]:
import tensorflow as tf
print(tf.__version__)

2.9.1


In [5]:
##tensorflow >2.0
from tensorflow.keras.preprocessing.text import one_hot

In [6]:
### sentences
sent=[  'the glass of milk',
     'the glass of juice',
     'the cup of tea',
    'I am a good boy',
     'I am a good developer',
     'understand the meaning of words',
     'your videos are good',]

In [7]:
sent

['the glass of milk',
 'the glass of juice',
 'the cup of tea',
 'I am a good boy',
 'I am a good developer',
 'understand the meaning of words',
 'your videos are good']

In [9]:
### Vocabulary size, its important to define vocab size
voc_size=10000

Now we will start one hot encoding process

In [11]:
onehot_repr=[one_hot(words,voc_size)for words in sent] 
print(onehot_repr)

#in the output below number - 7709(1st no) is one hot representation of word "the" in first sentence
#in one hot for each word it place 1 in the matrix and the position of that 1 in matrix for that word is the number 7709(mentioned above)
#each word of those sentences will hve its own matrix and nyumber will be th eindex of 1 in hat matrix


[[7709, 7704, 938, 7847], [7709, 7704, 938, 5937], [7709, 1937, 938, 321], [3437, 1157, 4649, 3873, 6798], [3437, 1157, 4649, 3873, 5592], [1796, 7709, 8015, 938, 298], [2207, 3233, 6123, 3873]]


In [13]:
"""
in neural network all inputs should have equal lenght/size, so inorder to make all the sentences 
of same size(currently they are not) we will use padding in text
"""

from tensorflow.keras.layers import Embedding
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.models import Sequential

import numpy as np

sent_length=8 #max lenght of the sentence currently that we have in data
embedded_docs=pad_sequences(onehot_repr,padding='pre',maxlen=sent_length)
print(embedded_docs)

#padding = pre means 0 will be added in first
#padding = post means 0 will be add in last

[[   0    0    0    0 7709 7704  938 7847]
 [   0    0    0    0 7709 7704  938 5937]
 [   0    0    0    0 7709 1937  938  321]
 [   0    0    0 3437 1157 4649 3873 6798]
 [   0    0    0 3437 1157 4649 3873 5592]
 [   0    0    0 1796 7709 8015  938  298]
 [   0    0    0    0 2207 3233 6123 3873]]


In [14]:
dim = 10
# 10 feature dimensions will be added

In [15]:
model=Sequential()
model.add(Embedding(voc_size,10,input_length=sent_length))
model.compile('adam','mse')

In [16]:
model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 embedding (Embedding)       (None, 8, 10)             100000    
                                                                 
Total params: 100,000
Trainable params: 100,000
Non-trainable params: 0
_________________________________________________________________


In [17]:
print(model.predict(embedded_docs))

1/1 [==============================] - 0s 62ms/step
[[[ 0.03715626 -0.02715619 -0.0137265   0.04332216 -0.00971509
   -0.04001409 -0.04952451 -0.02441324 -0.03287707 -0.02309494]
  [ 0.03715626 -0.02715619 -0.0137265   0.04332216 -0.00971509
   -0.04001409 -0.04952451 -0.02441324 -0.03287707 -0.02309494]
  [ 0.03715626 -0.02715619 -0.0137265   0.04332216 -0.00971509
   -0.04001409 -0.04952451 -0.02441324 -0.03287707 -0.02309494]
  [ 0.03715626 -0.02715619 -0.0137265   0.04332216 -0.00971509
   -0.04001409 -0.04952451 -0.02441324 -0.03287707 -0.02309494]
  [ 0.0020001   0.0258929  -0.03615554  0.01921645 -0.03406339
   -0.01137989  0.04111918 -0.00817855  0.00637326  0.03120146]
  [ 0.01379429  0.043233   -0.00775324  0.02840758  0.01892295
   -0.04555711 -0.03886463 -0.01624846 -0.03607786  0.0049625 ]
  [ 0.02389557  0.00145979 -0.02173133  0.03344036 -0.00587795
   -0.00986633  0.04538924  0.04305451 -0.00810928  0.02906373]
  [ 0.01896228  0.01520122 -0.04759847 -0.01688372 -0.01198

In [ ]:
embedded_docs[0]

In [ ]:
print(model.predict(embedded_docs)[0])